config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :seasons
  resources :episodes do
    resources :comments, only: [:create]
  end
  resources :series

  root to: "series#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :episodes

  validates :user, presence: true
  validates :restaurant, presence: true
  validates :text, length: { minimum: 5 }
end

app/models/episode.rb
class Episode < ApplicationRecord
  validates :name, presence: true
  belongs_to :season
  has_many :comments
end

app/models/season.rb
class Season < ApplicationRecord
  validates :num, presence: true
  
  belongs_to :serie
end

app/models/serie.rb
class Serie < ApplicationRecord
    mount_uploader :image, ImageUploader

    validates :image, presence: true
    validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
  
    def create
      @episode = Episode.find(params[:episode_id])
      @new_comment = Comment.new(comment_params)
      @new_comment.episode = @episode
      @new_comment.user = current_user
  
      if @new_comment.valid?
        @new_comment.save!
        flash[:notice] = "Votre commentaire a été ajouté."
        redirect_to episode_path(@episode)
      else
        render "espisodes/show"
      end
    end
  
    private
    def comment_params
      params.require(:comment).permit(:text)
    end
  end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :set_episode, only: [:show, :edit, :update, :destroy]

  # GET /episodes
  # GET /episodes.json
  def index
    @episodes = Episode.all
  end

  # GET /episodes/1
  # GET /episodes/1.json
  def show
    @episodes = Episode.where(season_id: params[:id])
  end

  # GET /episodes/new
  def new
    @episode = Episode.new
  end

  # GET /episodes/1/edit
  def edit
  end

  # POST /episodes
  # POST /episodes.json
  def create
    @episode = Episode.new(episode_params)

    respond_to do |format|
      if @episode.save
        format.html { redirect_to @episode, notice: 'Episode was successfully created.' }
        format.json { render :show, status: :created, location: @episode }
      else
        format.html { render :new }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /episodes/1
  # PATCH/PUT /episodes/1.json
  def update
    respond_to do |format|
      if @episode.update(episode_params)
        format.html { redirect_to @episode, notice: 'Episode was successfully updated.' }
        format.json { render :show, status: :ok, location: @episode }
      else
        format.html { render :edit }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /episodes/1
  # DELETE /episodes/1.json
  def destroy
    @episode.destroy
    respond_to do |format|
      format.html { redirect_to episodes_url, notice: 'Episode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episode
      @episode = Episode.where(episode_id: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def episode_params
      params.fetch(:episode, {})
    end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  before_action :set_season, only: [:show, :edit, :update, :destroy]

  # GET /seasons
  # GET /seasons.json
  def index
    # @season = Season.All
  end

  # GET /seasons/1
  # GET /seasons/1.json
  def show
    @seasons = Season.where(serie_id: params[:id])
  end

  # GET /seasons/new
  def new
    @season = Season.new
  end

  # GET /seasons/1/edit
  def edit
  end

  # POST /seasons
  # POST /seasons.json
  def create
    @season = Season.new(season_params)

    respond_to do |format|
      if @season.save
        format.html { redirect_to @season, notice: 'Season was successfully created.' }
        format.json { render :show, status: :created, location: @season }
      else
        format.html { render :new }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seasons/1
  # PATCH/PUT /seasons/1.json
  def update
    respond_to do |format|
      if @season.update(season_params)
        format.html { redirect_to @season, notice: 'Season was successfully updated.' }
        format.json { render :show, status: :ok, location: @season }
      else
        format.html { render :edit }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seasons/1
  # DELETE /seasons/1.json
  def destroy
    @season.destroy
    respond_to do |format|
      format.html { redirect_to seasons_url, notice: 'Season was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_season
      @seasons = Season.where(serie_id: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def season_params
      params.fetch(:season, {})
    end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :set_series, only: [:show, :edit, :update, :destroy]

  # GET /series
  # GET /series.json
  def index
    @series = Serie.all
  end

  # GET /series/1
  # GET /series/1.json
  def show
  end

  # GET /series/new
  def new
    @series = Serie.new
  end

  # GET /series/1/edit
  def edit
  end

  # POST /series
  # POST /series.json
  def create
    @series = Serie.new(series_params)

    respond_to do |format|
      if @series.save
        format.html { redirect_to @series, notice: 'Serie was successfully created.' }
        format.json { render :show, status: :created, location: @series }
      else
        format.html { render :new }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /series/1
  # PATCH/PUT /series/1.json
  def update
    respond_to do |format|
      if @series.update(series_params)
        format.html { redirect_to @series, notice: 'Serie was successfully updated.' }
        format.json { render :show, status: :ok, location: @series }
      else
        format.html { render :edit }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1
  # DELETE /series/1.json
  def destroy
    @series.destroy
    respond_to do |format|
      format.html { redirect_to series_url, notice: 'Serie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @series = Serie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def series_params
      params.fetch(:series, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/comments/_form.html.erb
<h4>Ajoutez votre commentaire :</h4>
<%= simple_form_for([episode, comment]) do |f| %>
  <%= f.input :text, label: false %>
  <%= f.button :submit %>
<% end %>

app/views/comments/_show.html.erb
<section class="comment">
  <blockquote>
    <%= comment.text %>
  </blockquote>
  <p class="small text-right">Par <%= comment.user.username %>
    le <%= l(comment.created_at.to_date, format: "%d/%m/%Y") %></p>
</section>

# app/views/restaurants/show.html.erb
<div class="comments">
  <% if @episode.comments.any? %>
    <h2>Commentaires:</h2>

    <% @episode.comments.each do |comment| %>
      <%= render "comments/show", comment: comment %>
    <% end %>
  <% end %>
</div>

app/views/episodes/_form.html.erb
<%= form_with(model: episode, local: true) do |form| %>
  <% if episode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(episode.errors.count, "error") %> prohibited this episode from being saved:</h2>

      <ul>
      <% episode.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<h1>Editing Episode</h1>

<%= render 'form', episode: @episode %>

<%= link_to 'Show', @episode %> |
<%= link_to 'Back', episodes_path %>

app/views/episodes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Episodes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @episodes.each do |episode| %>
      <tr>
        <td><%= link_to 'Show', episode %></td>
        <td><%= link_to 'Edit', edit_episode_path(episode) %></td>
        <td><%= link_to 'Destroy', episode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Episode', new_episode_path %>

app/views/episodes/new.html.erb
<h1>New Episode</h1>

<%= render 'form', episode: @episode %>

<%= link_to 'Back', episodes_path %>

app/views/episodes/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Episodes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @episodes.each do |episodes| %>
      <tr>
        <td> <td><%= link_to episodes.name, episode_path(episodes.season_id) %></td> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', series_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FanSeries</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/seasons/_form.html.erb
<%= form_with(model: season, local: true) do |form| %>
  <% if season.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(season.errors.count, "error") %> prohibited this season from being saved:</h2>

      <ul>
      <% season.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/seasons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Seasons</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @seasons.each do |season| %>
      <tr>
        <td><%= link_to season.num, Episode %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/seasons/show.html.erb
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
  <!-- <link rel="stylesheet" href="css/style.css"> -->
  <%= stylesheet_link_tag    'application', media: 'all' %>
</head>

<body>

  <div class="container">


    <div class="row">
      <div class="col-12 saison">
      </div>
    </div>

    <div class="row episode-list">

      <% @seasons.each do |seasons| %>
      <div class="col-lg-4 col-md-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= link_to seasons.num, episode_path(seasons) %></h5>
          </div>
        </div>
      </div>
      <% end %>

    </div>

  </div>

</body>

app/views/series/_form.html.erb
<%= form_with(model: series, local: true) do |form| %>
  <% if series.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(series.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
      <% series.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/series/edit.html.erb
<h1>Editing Series</h1>

<%= render 'form', series: @series %>

<%= link_to 'Show', @series %> |
<%= link_to 'Back', series_path %>

app/views/series/index.html.erb
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all' %>

  <!-- <link rel="stylesheet" href="asset/stylesheets/series.scss"> -->
</head>
<body>
  <div class="container">

    <!-- nav barre -->
    

    
    <!-- fin nav barre -->

    <div class="row list-movie">

      <% @series.each do |series| %>
      <div class="col-lg-4 col-md-6">
        <div class="card">
          <!-- <img class="card-img-top" src=""> -->
          <%= cl_image_tag series.image, class: "card-img-top" %>
          <div class="card-body">
            <h5 class="card-title"><%= link_to series.name, season_path(series) %></h5>
          </div>
        </div>
      </div>
      <% end %>


    </div>

  </div>
</body>

app/views/series/new.html.erb
<h1>New Series</h1>

<%= render 'form', series: @series %>

<%= link_to 'Back', series_path %>

app/views/series/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_series_path(@series) %> |
<%= link_to 'Back', series_path %>

app/views/shared/_navbar.html.erb
<div class="row nav">

      <div class="col">
        <h2 onclick="location.href='index.html'">FanSerie</h2>
      </div>

      <div class="col-5">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Recherche" aria-label="Recherche" aria-describedby="basic-addon2">
          <div class="input-group-append">
            <button class="btn btn-outline-secondary" type="button"><i class="fas fa-search"></i></button>
          </div>
        </div>
      </div>

      <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
              aria-haspopup="true" aria-expanded="false">
                Bienvenue, <%= current_user.email %>
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to edit_user_registration_path do %>
                  <i class="fa fa-user"></i> Modifier le profil
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i> Déconnexion
                <% end %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to("Connexion", new_user_session_path) %></li>
          <li><%= link_to("Inscription", new_user_registration_path) %></li>
        <% end %>
      </ul>
    </div>
    </div>